name: Build Video
on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contents
        uses: actions/checkout@v2
      - name: Create Kind Cluster
        uses: helm/kind-action@v1.2.0
        with: 
          config: files/kind-config.yml
      - name: Install Ingress
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl wait --for=condition=Available --timeout=500s -n ingress-nginx deployment/ingress-nginx-controller
          kubectl rollout status -n ingress-nginx deployment/ingress-nginx-controller -w
          kubectl wait --for=condition=Ready --timeout=500s -n ingress-nginx -l app.kubernetes.io/component=controller pod
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Install Cert-manager
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.5.1
          kubectl wait --for=condition=Available --timeout=500s -n cert-manager deployment/cert-manager
      - name: Install Rancher
        run: |
          kubectl create namespace cattle-system
          helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
          helm repo update
          helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=localhost --set bootstrapPassword=admin --set replicas=1
          kubectl wait --for=condition=Available --timeout=500s -n cattle-system deployment/rancher
          kubectl patch settings first-login --type='json' -p='[{"op": "replace", "path": "/value", "value": "false"}]'
          kubectl patch user $(kubectl get user -l authz.management.cattle.io/bootstrapping=admin-user -o jsonpath='{.items[*].metadata.name}') --type='json' -p='[{"op": "replace", "path": "/mustChangePassword", "value": False}]'
          kubectl create namespace $(kubectl get user -l authz.management.cattle.io/bootstrapping=admin-user -o jsonpath='{.items[*].metadata.name}')
          kubectl apply -f files/userPreferences.yml -n $(kubectl get user -l authz.management.cattle.io/bootstrapping=admin-user -o jsonpath='{.items[*].metadata.name}')
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Playwright
        run: |
          pip install playwright
          pip install pytest
          playwright install
          pip install pytest-playwright
      - name: Generate Artifact
        continue-on-error: true
        run: |
          pytest test-canvas.py --video on --slowmo 10
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: videos
      - uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: videos 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
